version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gha-version-updates:
        applies-to: version-updates
        patterns: ["*"]
